### ISSUE TITLE
Roadmap or target

### ISSUE THREAD

**Issue by djKooks** [svenkreiss/databench#19]
Hello. I'm looking over some data analysis / research tools, and this seems quite simple and good.
This is just a question. Do you have some kind of roadmap or plan for updating this project?

**Comment by svenkreiss** [comment]
Not really. I am trying to maintain a consistent API while adding features that come up for me.
What are your use cases? Where do you want to see Databench go?

**Comment by djKooks** [comment]
Thanks for reply!
I don't have specific use case yet, but interest in data research and make visualize(and also working on it). It seems like it is focusing on connection of data analysis and visualization more simply and it looks quite good. I'll keep trying on it and let you know if there are some good suggestion.

**Comment by svenkreiss** [comment]
Sounds good. Let me know how it goes and also if you discover something
strange or missing.
