### ISSUE TITLE
Manage log level

### ISSUE THREAD

**Issue by djKooks** [svenkreiss/databench#20]
Hello @svenkreiss 
I could see addr and port info by setup log to DEBUG, but not when removing this part. For example, when I run with just using `databench` command, I couldn't see nothing.
How about make part below to be shown whether any log level is selected?
```
INFO:root:Databench 0.6.0
INFO:root:host=localhost, port=5000
```
It looks like it is simple by just change some part in cli.py : main() ,but I hope to know if you have other suggestion about it.

Thanks.

**Comment by svenkreiss** [comment]
Thanks for bringing this up. 

How about this: given that databench's main input and output methods are the browser and not the terminal, we can break the convention and instead of `WARNING` being the default log level we can make `INFO` the default. 

Would that solve it for you? You can test it with `databench --log INFO`.

**Comment by djKooks** [comment]
@svenkreiss Thanks for reply!
What I am thinking is, maybe sometimes developer could forgot the port number to access, and also forgot how to input log info. It could be pretty silly, but can be happen.

When I input `databench --log INFO`
```
Setting loglevel to INFO.
INFO:root:Python 3.5.1 (default, May 19 2016, 19:12:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
INFO:root:Databench 0.6.0
INFO:root:host=localhost, port=5000
WARNING:databench.app:Did not find "analyses" module. Using packaged analyses.
INFO:databench.app:Registering meta information dummypi
INFO:databench.app:Registering meta information scaffold
INFO:databench.app:Registering meta information dummypi_py
INFO:databench.app:Registering meta information scaffold_py
INFO:databench.app:watching additional files: ['dummypi/*.js', 'dummypi/*.html', 'scaffold/*.js', 'scaffold/*.html', 'dummypi_py/*.js', 'dummypi_py/*.html', 'dummypi_py/*.py', 'scaffold_py/*.js', 'scaffold_py/*.html', 'scaffold_py/*.py']
```
and this is when I input just `databench`
```
WARNING:databench.app:Did not find "analyses" module. Using packaged analyses.
```
So suggestion is, how about make calling port number and databench version with `print` module to make it default to show? It could be awkward to make as WARNING level.

This is very trivial part, and I'm not sure if it is a good suggestion. If you think it make sense, please let me know than I'll update it. Or please close the issue.

Thanks.

**Comment by svenkreiss** [comment]
I am in general against polluting stdout, but you make a good point and in this case it is the main information that is necessary here.

Do you want to submit a pull request with that change?

**Comment by svenkreiss** [comment]
Thanks!
