### ISSUE TITLE
Trunk lacks databench.js

### ISSUE THREAD

**Issue by orangkucing** [svenkreiss/databench#57]
It seems databench/static/databench.js is mistakenly omitted to push to the repo since commit 1d77735d5cd0cc7119bf38d11eb941f909029b70 of 11 Jun 2016.  Is it OK?

**Comment by svenkreiss** [comment]
It is ok. The frontend is now written in TypeScript. The source files are in the `js/src` folder. Running

```sh
npm install
webpack
```

should generate the `databench/static/databench.js` file. It is also a `node` package now in case you need to use it as part of some other JavaScript build process.

**Comment by svenkreiss** [comment]
... and the generated file is part of the source and binary distributions on pypi. So `pip install databench` gives you everything including the generated JavaScript file.

**Comment by orangkucing** [comment]
Thank you! It works like a charm.

---=^..^= Hisashi ITO
⌘
